name: quantify_example
description: A command-line example for the quantify package.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.19.0
  quantify: ^0.2.0


dev_dependencies:
  test: ^1.26.0
  very_good_analysis: ^8.0.0
