name: quantify_example
description: A command-line example for the quantify package.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  intl: ^0.20.2
  quantify: ^0.18.0

dev_dependencies:
  test: ^1.31.0
  very_good_analysis: ^10.2.0
